using System;
using System.Text;

namespace YAMCqrs.EventBus.Core.SourceGeneration.GeneratorHelper
{
    internal static class DependencyInjectionHelper
    {
        public static string GenerateCode()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"// Generation Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
            sb.AppendLine("#nullable enable");

            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Microsoft.Extensions.Logging;");
            sb.AppendLine(Const.Usings.Extensions);
            sb.AppendLine(Const.Usings.IEventDispatcher);
            sb.AppendLine(Const.Usings.ITopicToCommand);
            sb.AppendLine(Const.Usings.Configuration);
            sb.AppendLine(Const.Usings.StaticServiceCollectionExtensions);
            sb.AppendLine();
            sb.AppendLine(Const.NamespaceName);
            sb.AppendLine();

            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Generated service registration extensions");
            sb.AppendLine("/// </summary>");


            sb.AppendLine("public static class ServiceCollectionExtensions");
            sb.AppendLine("{");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated service registration extensions");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static IEventBusBuilder AddEventBus(this IServiceCollection services, Action<EventBusConfiguration>? configure = null)");
            sb.AppendLine("    {");
            sb.AppendLine("        var config = new EventBusConfiguration();");
            sb.AppendLine("        configure?.Invoke(config);");
            sb.AppendLine("        return services.AddServiceBusCqrs(config);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Shhh this is private, you can see it");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    private static IEventBusBuilder AddServiceBusCqrs(this IServiceCollection services, EventBusConfiguration cfg)");
            sb.AppendLine("    {");
            sb.AppendLine("     services.ExtendEventBusCqrs(cfg);");
            sb.AppendLine("     services.AddSingleton<IEventDispatcher, EventDispatcher>();");
            sb.AppendLine("     services.AddSingleton<ITopicToCommand, TopicToCommand>();");
            sb.AppendLine("     return new EventBusBuilder(services, cfg);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

    }
}
