using System.Text;

namespace YAMCqrs.EventBus.Provider.Kafka.SourceGeneration.GeneratorHelper;

internal static class DependencyInjectionHelper
{
    public static string GenerateCode(string[] topics)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine(Const.Usings.Extensions);
        sb.AppendLine(Const.Usings.Options);
        sb.AppendLine(Const.Usings.StaticServiceCollectionExtensions);

        sb.AppendLine();
        sb.AppendLine(Const.NamespaceName);
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods for registering Kafka output event handlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class ServiceCollectionExtension");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Topics extracted from KafkaSubscribeEvent classes.");
        sb.AppendLine("    /// </summary>");

        if (topics.Length == 0)
        {
            sb.AppendLine("    private static readonly string[] KafkaTopics = System.Array.Empty<string>();");
        }
        else
        {
            sb.AppendLine("    private static readonly string[] KafkaTopics = new[]");
            sb.AppendLine("    {");
            foreach (var topic in topics)
            {
                sb.AppendLine($"        \"{topic}\",");
            }
            sb.AppendLine("    };");
        }

        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all Kafka output event handlers with their corresponding PublishEventHandler.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"builder\">Builder.</param>");
        sb.AppendLine("    /// <param name=\"options\">Options.</param>");
        sb.AppendLine("    /// <returns>The service collection for chaining.</returns>");
        sb.AppendLine("    public static IEventBusBuilder UseKafka(this IEventBusBuilder builder, KafkaConfigurationOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        return builder.ExtendUseKafka(options, KafkaTopics);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
