using System;
using System.Text;

namespace YAMCqrs.ServiceBus.Core.SourceGeneration.GeneratorHelper
{
    internal static class DependencyInjectionHelper
    {
        public static string GenerateCode()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"// Generation Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
            sb.AppendLine("#nullable enable");

            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine(Const.Usings.Extensions);
            sb.AppendLine(Const.Usings.IEventDispatcher);
            sb.AppendLine(Const.Usings.ITopicToCommand);
            sb.AppendLine();
            sb.AppendLine(Const.NamespaceName);
            sb.AppendLine();

            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Generated service registration extensions");
            sb.AppendLine("/// </summary>");


            sb.AppendLine("public static class ServiceCollectionExtensions");
            sb.AppendLine("{");

            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated service registration extensions");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void AddServiceBusCqrs(this IServiceCollection services)");
            sb.AppendLine("    {");
            sb.AppendLine("     services.ExtendServiceBusCqrs();");
            sb.AppendLine("     services.AddSingleton<IEventDispatcher, EventDispatcher>();");
            sb.AppendLine("     services.AddSingleton<ITopicToCommand, TopicToCommand>();");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

    }
}
