using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YAMCqrs.ServiceBus.Core.SourceGeneration.Info;

namespace YAMCqrs.ServiceBus.Core.SourceGeneration.GeneratorHelper;

internal static class EventDispatcherHelper
{
    public static string GenerateCode(List<EventHandlerInfo> eventHandlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generation Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine(Const.Usings.IEventDispatcher);
        sb.AppendLine();
        sb.AppendLine(Const.NamespaceName);
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("///Generated event dispatcher with zero reflection overhead.");
        sb.AppendLine("///Combines event dispatching and deserialization in a single service.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed class EventDispatcher : IEventDispatcher");
        sb.AppendLine("{");

        var allEventTypes = eventHandlers
            .SelectMany(h => h.EventTypes)
            .Distinct()
            .ToList();

        // ========== Diccionario de Deserializadores ==========
        sb.AppendLine("     /// <summary>");
        sb.AppendLine("     ///Event type deserializers (compiled delegates, zero reflection)");
        sb.AppendLine("     /// </summary>");

        sb.AppendLine("     private static readonly Dictionary<string, Func<string, object>> _deserializers = new()");
        sb.AppendLine("     {");

        foreach (var eventType in allEventTypes)
        {
            var typeName = eventType.Split('.').Last();
            sb.AppendLine($"        [\"{typeName}\"] = json => JsonSerializer.Deserialize<{eventType}>(json)!,");
        }
        sb.AppendLine("     };");

        // ========== Mapeo de Nombres ==========
        sb.AppendLine("     /// <summary>");
        sb.AppendLine("     ///Mapping from fully qualified names to simple names");
        sb.AppendLine("     /// </summary>");
        sb.AppendLine("     private static readonly Dictionary<string, string> _typeNameMapping = new()");
        sb.AppendLine("     {");

        foreach (var eventType in allEventTypes)
        {
            var typeName = eventType.Split('.').Last();
            sb.AppendLine($"        [\"{eventType}\"] = \"{typeName}\",");
        }
        sb.AppendLine("     };");
        sb.AppendLine();

        // ========== DeserializeEvent Method ==========
        sb.AppendLine("     public object? DeserializeEvent(string eventType, string json)");
        sb.AppendLine("     {");
        sb.AppendLine("         if (_deserializers.TryGetValue(eventType, out var deserializer))");
        sb.AppendLine("             return deserializer(json);");
        sb.AppendLine();
        sb.AppendLine("         if (_typeNameMapping.TryGetValue(eventType, out var simpleName) &&");
        sb.AppendLine("             _deserializers.TryGetValue(simpleName, out deserializer))");
        sb.AppendLine("             return deserializer(json);");
        sb.AppendLine();
        sb.AppendLine("         return null;");
        sb.AppendLine("     }");
        sb.AppendLine();
        // ========== GetEventTypeName Method ==========
        sb.AppendLine("     public string? GetEventTypeName(string eventType)");
        sb.AppendLine("     {");
        sb.AppendLine("         if (_typeNameMapping.TryGetValue(eventType, out var simpleName))");
        sb.AppendLine("          return simpleName;");
        sb.AppendLine();
        sb.AppendLine("         return _deserializers.ContainsKey(eventType) ? eventType : null;");
        sb.AppendLine("     }");
        sb.AppendLine();
        // ========== DispatchAsync Method ==========
        sb.AppendLine("     public async Task<bool> DispatchAsync(string eventTypeName, object @event ,IServiceProvider serviceProvider,CancellationToken cancellationToken = default)");
        sb.AppendLine("     {");
        sb.AppendLine("         switch (eventTypeName)");
        sb.AppendLine("         {");

        // Generar case para cada tipo de evento
        var processedEventTypes = new HashSet<string>();
        foreach (var eventHandler in eventHandlers)
        {
            foreach (var eventType in eventHandler.EventTypes)
            {
                if (!processedEventTypes.Add(eventType))
                    continue;

                sb.AppendLine($"            case \"{eventType}\":");
                sb.AppendLine($"                await DispatchTypedAsync(({eventType})@event, serviceProvider, cancellationToken);");
                sb.AppendLine($"                return true;");
                sb.AppendLine();
            }
        }
        sb.AppendLine("                     //No handler found");
        sb.AppendLine("            default:");
        sb.AppendLine("                return false;");
        sb.AppendLine("     }");
        sb.AppendLine("}");
        sb.AppendLine();
        // ========== DispatchTypedAsync Methods ==========
        processedEventTypes.Clear();
        foreach (var eventHandler in eventHandlers)
        {
            foreach (var eventType in eventHandler.EventTypes)
            {
                if (!processedEventTypes.Add(eventType))
                    continue;

                sb.AppendLine($"    private static async Task DispatchTypedAsync({eventType} @event, IServiceProvider serviceProvider, CancellationToken cancellationToken)");
                sb.AppendLine("     {");
                sb.AppendLine($"        var handlers = serviceProvider.GetServices<IEventHandler<{eventType}>>();");
                sb.AppendLine("         foreach (var handler in handlers)");
                sb.AppendLine("         {");
                sb.AppendLine("             await handler.HandleAsync(@event, cancellationToken);");
                sb.AppendLine("         }");
                sb.AppendLine("     }");
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
