using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using YAMCqrs.ServiceBus.Core.SourceGeneration.Info;

namespace YAMCqrs.ServiceBus.Core.SourceGeneration.GeneratorHelper;

internal static class TopicToCommandHelper
{
    public static string GenerateCode(List<CqrsInfo> mappings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine(Const.Usings.CoreExtensions);
        sb.AppendLine(Const.Usings.ITopicToCommand);
        sb.AppendLine();
        
        sb.AppendLine(Const.NamespaceName);
        sb.AppendLine();
        
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated mapping of Service Bus topics to their corresponding event types.");
        sb.AppendLine($"/// Contains {mappings.Count} registered topic mapping(s).");
        sb.AppendLine("/// Uses switch-based lookups for optimal performance.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class TopicToCommand : ITopicToCommand");
        sb.AppendLine("{");

        // Generate IsEmpty
        GenerateIsEmpty(sb, mappings);
        sb.AppendLine();

        GenerateDeserializerTopic(sb, mappings);
        sb.AppendLine();

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateIsEmpty(StringBuilder sb, List<CqrsInfo> mappings)
    {
        var returnValue = mappings.Count == 0 ? "true" : "false";

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Indica si el mapa de topics está vacío.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <returns><c>true</c> si no hay mappings registrados; de lo contrario, <c>false</c>.</returns>");
        sb.AppendLine("    public bool IsEmpty()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return {returnValue};");
        sb.AppendLine("    }");
    }

    private static void GenerateDeserializerTopic(StringBuilder sb, List<CqrsInfo> mappings)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Attempts to deserialize a JSON message to its corresponding ServiceBusSubscribeEvent type based on topic.");
        sb.AppendLine("    /// This method uses direct type deserialization without reflection for maximum performance.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"topic\">The Service Bus topic name.</param>");
        sb.AppendLine("    /// <param name=\"jsonMessage\">The JSON message to deserialize.</param>");
        sb.AppendLine("    /// <param name=\"command\">The deserialized event instance if successful; otherwise, null.</param>");
        sb.AppendLine("    /// <returns>true if deserialization succeeded; otherwise, false.</returns>");
        sb.AppendLine("    public bool TryDeserializerTopic(string topic, string jsonMessage, out SubscribeEvent? command)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            command = topic switch");
        sb.AppendLine("            {");

        foreach (var item in mappings)
        {
            var cleanFullName = item.FullTypeName.Replace("global::", "").Trim();
            sb.AppendLine($"                \"{EscapeString(item.Topics.FirstOrDefault())}\" => JsonSerializer.Deserialize<{cleanFullName}>(jsonMessage, JsonSerializerExtensions.JsonSerializerOptions),");
        }

        sb.AppendLine("                _ => null");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            return command is not null;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (JsonException)");
        sb.AppendLine("        {");
        sb.AppendLine("            command = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
