using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YAMCqrs.Core.SourceGeneration;
using YAMCqrs.Core.SourceGeneration.Info;

internal static class DependencyInjectionHelper
{
    private static StringBuilder _sb;

    public static string GenerateCode(
        List<HandlerInfo> handlers,
        List<InterceptorInfo> interceptors)
    {
        _sb = new StringBuilder();
        _sb.AppendLine("// <auto-generated />");
        _sb.AppendLine($"// Generation Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        _sb.AppendLine("#nullable enable");

        _sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _sb.AppendLine(Const.Usings.ICommand);
        _sb.AppendLine(Const.Usings.IQuery);
        _sb.AppendLine(Const.Usings.IDispatcher);

        _sb.AppendLine();
        _sb.AppendLine(Const.NamespaceName);
        _sb.AppendLine();

        _sb.AppendLine("/// <summary>");
        _sb.AppendLine("/// Generated service registration extensions");
        _sb.AppendLine("/// </summary>");


        _sb.AppendLine("public static class ServiceCollectionExtensions");
        _sb.AppendLine("{");

        _sb.AppendLine("    /// <summary>");
        _sb.AppendLine("    /// Generated service registration extensions");
        _sb.AppendLine("    /// </summary>");
        _sb.AppendLine("    public static void AddYAMCqrs(this IServiceCollection services)");
        _sb.AppendLine("    {");

        //Registrar Dispatcher
        _sb.AppendLine("        //Register command/query dispatcher");
        _sb.AppendLine("        services.AddScoped<IDispatcher, Dispatcher>();");

        // ========== Register Command Handlers ==========
        var allCommandHandlers = handlers
            .SelectMany(h => h.CommandTypes.Select(ct => (Handler: h.FullTypeName, Command: ct)))
            .ToList();

        // ========== Register Query Handlers ==========
        var allQueryHandlers = handlers
            .SelectMany(h => h.QueryTypes.Select(qt => (Handler: h.FullTypeName, Query: qt)))
            .ToList();

        // ========== Validate 1:1 Command/Query → Handler constraint ==========
        var commandDuplicates = allCommandHandlers
            .GroupBy(x => (x.Command.CommandType, x.Command.ResultType))
            .Where(g => g.Count() > 1)
            .Select(g =>
                $"ICommandHandler<{g.Key.CommandType}, {g.Key.ResultType}> has multiple handlers: " +
                string.Join(", ", g.Select(x => x.Handler)))
            .ToList();

        var queryDuplicates = allQueryHandlers
            .GroupBy(x => (x.Query.QueryType, x.Query.ResultType))
            .Where(g => g.Count() > 1)
            .Select(g =>
                $"IQueryHandler<{g.Key.QueryType}, {g.Key.ResultType}> has multiple handlers: " +
                string.Join(", ", g.Select(x => x.Handler)))
            .ToList();

        var allDuplicates = commandDuplicates.Concat(queryDuplicates).ToList();

        if (allDuplicates.Count > 0)
        {
            var errorLines = string.Join("\\n  - ", allDuplicates);
            _sb.AppendLine("        //CQRS CONFIGURATION ERROR — detected at source generation time.");
            _sb.AppendLine("        Each ICommand<TResult> and IQuery<TResult> must have exactly one handler.");

            _sb.AppendLine(
                $"      throw new System.InvalidOperationException(" +
                $"\"CQRS configuration error: the 1-to-1 constraint between command/query and handler was violated.\\n" +
                $"  - {errorLines}\");");
        }

        _sb.AppendLine("        //Register command handlers");

        if (allCommandHandlers.Count > 0)
        {
            foreach (var (handler, command) in allCommandHandlers)
            {
                _sb.AppendLine($"       services.AddScoped<ICommandHandler<{command.CommandType}, {command.ResultType}>, {handler}>();");
            }
        }

        _sb.AppendLine("        //Register query handlers");
        if (allQueryHandlers.Count > 0)
        {
            foreach (var (handler, query) in allQueryHandlers)
            {
                _sb.AppendLine($"       services.AddScoped<IQueryHandler<{query.QueryType}, {query.ResultType}>, {handler}>();");
            }
        }

        // ========== Register Command Interceptors con filtro ==========
        var commandInterceptors = interceptors
            .Where(i => i.CommandTypes.Length > 0)
            .ToList();

        _sb.AppendLine("        //Register command interceptors (respecting disabled list)");
        if (commandInterceptors.Count > 0)
        {
            foreach (var interceptor in commandInterceptors)
            {
                _sb.AppendLine($"       //Interceptor: {interceptor.FullTypeName}");

                var typeofExpression = interceptor.IsGenericDefinition
                    ? $"typeof({interceptor.FullTypeNameWithoutGenerics}<,>)"
                    : $"typeof({interceptor.FullTypeName})";

                if (interceptor.IsGenericDefinition)
                {
                    _sb.AppendLine($"           services.AddScoped(typeof(ICommandInterceptor<,>), typeof({interceptor.FullTypeNameWithoutGenerics}<,>));");
                }
                else
                {
                    foreach (var (CommandType, ResultType) in interceptor.CommandTypes)
                    {
                        _sb.AppendLine($"           services.AddScoped<ICommandInterceptor<{CommandType}, {ResultType}>, {interceptor.FullTypeName}>();");
                    }
                }
            }
        }

        // ========== Register Query Interceptors con filtro ==========
        var queryInterceptors = interceptors
            .Where(i => i.QueryTypes.Length > 0)
            .ToList();

        _sb.AppendLine("        //Register query interceptors (respecting disabled list)");
        if (queryInterceptors.Count > 0)
        {
            foreach (var interceptor in queryInterceptors)
            {
                _sb.AppendLine($"       //Interceptor: {interceptor.FullTypeName}");

                var typeofExpression = interceptor.IsGenericDefinition
                    ? $"typeof({interceptor.FullTypeNameWithoutGenerics}<,>)"
                    : $"typeof({interceptor.FullTypeName})";

                if (interceptor.IsGenericDefinition)
                {
                    _sb.AppendLine($"           services.AddScoped(typeof(IQueryInterceptor<,>), typeof({interceptor.FullTypeNameWithoutGenerics}<,>));");
                }
                else
                {
                    foreach (var (QueryType, ResultType) in interceptor.QueryTypes)
                    {
                        _sb.AppendLine($"           services.AddScoped<IQueryInterceptor<{QueryType}, {ResultType}>, {interceptor.FullTypeName}>();");
                    }
                }
            }
        }

        _sb.AppendLine("    }");
        _sb.AppendLine("}");

        return _sb.ToString();
    }
}
