using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YAMCqrs.Core.SourceGeneration.Info;

namespace YAMCqrs.Core.SourceGeneration.GeneratorHelper;

internal static class DispatcherHelper
{
    private static StringBuilder _sb;

    public static string GenerateCode(List<HandlerInfo> handlers)
    {
        _sb = new StringBuilder();

        // Collect all unique commands and queries with their result types
        var allCommands = handlers
            .SelectMany(h => h.CommandTypes)
            .Distinct()
            .ToList();

        var allQueries = handlers
            .SelectMany(h => h.QueryTypes)
            .Distinct()
            .ToList();

        _sb.AppendLine("// <auto-generated />");
        _sb.AppendLine($"// Generation Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        _sb.AppendLine("#nullable enable");
        _sb.AppendLine("using System;");
        _sb.AppendLine("using System.Linq;");
        _sb.AppendLine("using System.Threading;");
        _sb.AppendLine("using System.Threading.Tasks;");
        _sb.AppendLine("using System.Transactions;");
        _sb.AppendLine("using System.Collections.Concurrent;");
        _sb.AppendLine("using System.Collections.Generic;");
        _sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _sb.AppendLine(Const.Usings.ICommand);
        _sb.AppendLine(Const.Usings.IQuery);
        _sb.AppendLine(Const.Usings.IDispatcher);

        _sb.AppendLine();
        _sb.AppendLine("namespace YAMCqrs.Core;");
        _sb.AppendLine();
        _sb.AppendLine("/// <summary>");
        _sb.AppendLine("/// Initializes a new instance of the <see cref=\"Dispatcher\"/> class.");
        _sb.AppendLine("/// </summary>");
        _sb.AppendLine("/// <param name=\"_serviceProvider\">The service provider.</param>");
        _sb.AppendLine("internal sealed class Dispatcher(IServiceProvider _serviceProvider) : IDispatcher");
        _sb.AppendLine("{");

        GenerateCacheDictionary(allCommands, allQueries);
        _sb.AppendLine();
        if (allCommands.Count > 0)
        {
            GenerateGetOrderedCommandInterceptorsMethod();
        }
        else
        {
            _sb.AppendLine("    /// <summary>");
            _sb.AppendLine("    /// No command handlers registered - skipping command interceptor method generation");
            _sb.AppendLine("    /// </summary>");
        }
        _sb.AppendLine();
        if (allQueries.Count > 0)
        {
            GenerateGetOrderedQueryInterceptorsMethod();
        }
        else
        {
            _sb.AppendLine("    /// <summary>");
            _sb.AppendLine("    /// No query handlers registered - skipping query interceptor method generation");
            _sb.AppendLine("    /// </summary>");
        }
        _sb.AppendLine();
        GenerateSendAsyncMethod(allCommands);
        _sb.AppendLine();
        GenerateQueryAsyncMethod(allQueries);

        _sb.Append("}");

        return _sb.ToString();
    }

    private static void GenerateCacheDictionary(List<(string CommandType, string ResultType)> allCommands, List<(string QueryType, string ResultType)> allQueries)
    {
        if (allCommands.Count == 0 && allQueries.Count == 0)
            return;

        _sb.AppendLine("    /// <summary>");
        _sb.AppendLine("    /// Cache only the sorted type order — no live instances stored");
        _sb.AppendLine("    /// </summary>");
        _sb.AppendLine("    private static readonly ConcurrentDictionary<Type, Type[]> _interceptorTypeOrderCache = new();");
    }

    private static void GenerateGetOrderedCommandInterceptorsMethod()
    {
        _sb.AppendLine("    /// <summary>");
        _sb.AppendLine("    /// Resolves fresh interceptor instances per scope, using cached type sort order");
        _sb.AppendLine("    /// </summary>");
        _sb.AppendLine("    private IReadOnlyList<ICommandInterceptor<TCommand, TResult>> GetOrderedCommandInterceptors<TCommand, TResult>() where TCommand : ICommand<TResult>");
        _sb.AppendLine("    {");

        _sb.AppendLine("        //Always resolve FRESH instances from the current scope");
        _sb.AppendLine("        var interceptors = _serviceProvider");
        _sb.AppendLine("        .GetServices<ICommandInterceptor<TCommand, TResult>>()");
        _sb.AppendLine("        .ToList();");
        _sb.AppendLine("        if (interceptors.Count <= 1)");
        _sb.AppendLine("            return interceptors;");
        _sb.AppendLine("        var cacheKey = typeof(ICommandInterceptor<TCommand, TResult>);");
        _sb.AppendLine("        //Cache only the sorted Type[] — types are static, instances are not");
        _sb.AppendLine("        var sortedTypes = _interceptorTypeOrderCache.GetOrAdd(cacheKey, _ =>");
        _sb.AppendLine("        {");

        _sb.AppendLine("            var copy = interceptors.ToList();");
        _sb.AppendLine("            copy.Sort((a, b) =>");
        _sb.AppendLine("            {");
        _sb.AppendLine("                var layerComp = ((int)a.Layer).CompareTo((int)b.Layer);");
        _sb.AppendLine("                return layerComp != 0 ? layerComp : a.Order.CompareTo(b.Order);");
        _sb.AppendLine("            });");
        _sb.AppendLine("            return copy.Select(i => i.GetType()).ToArray();");
        _sb.AppendLine("        });");

        _sb.AppendLine("        //Return fresh instances ordered by the cached type sort");
        _sb.AppendLine("        return sortedTypes");
        _sb.AppendLine("        .Select(t => interceptors.First(i => i.GetType() == t))");
        _sb.AppendLine("        .ToList();");

        _sb.AppendLine("    }");
    }

    private static void GenerateGetOrderedQueryInterceptorsMethod()
    {
        _sb.AppendLine("    /// <summary>");
        _sb.AppendLine("    /// Resolves fresh interceptor instances per scope, using cached type sort order");
        _sb.AppendLine("    /// </summary>");
        _sb.AppendLine("    private IReadOnlyList<IQueryInterceptor<TQuery, TResult>> GetOrderedQueryInterceptors<TQuery, TResult>() where TQuery : IQuery<TResult>");
        _sb.AppendLine("    {");

        _sb.AppendLine("        //Always resolve FRESH instances from the current scope");
        _sb.AppendLine("        var interceptors = _serviceProvider");
        _sb.AppendLine("        .GetServices<IQueryInterceptor<TQuery, TResult>>()");
        _sb.AppendLine("        .ToList();");
        _sb.AppendLine("        if (interceptors.Count <= 1)");
        _sb.AppendLine("            return interceptors;");
        _sb.AppendLine("        var cacheKey = typeof(IQueryInterceptor<TQuery, TResult>);");
        _sb.AppendLine("        //Cache only the sorted Type[] — types are static, instances are not");
        _sb.AppendLine("        var sortedTypes = _interceptorTypeOrderCache.GetOrAdd(cacheKey, _ =>");
        _sb.AppendLine("        {");
        _sb.AppendLine("            var copy = interceptors.ToList();");
        _sb.AppendLine("            copy.Sort((a, b) =>");
        _sb.AppendLine("            {");
        _sb.AppendLine("                var layerComp = ((int)a.Layer).CompareTo((int)b.Layer);");
        _sb.AppendLine("                return layerComp != 0 ? layerComp : a.Order.CompareTo(b.Order);");
        _sb.AppendLine("            });");
        _sb.AppendLine("        return copy.Select(i => i.GetType()).ToArray();");
        _sb.AppendLine("        });");

        _sb.AppendLine("    //Return fresh instances ordered by the cached type sort");
        _sb.AppendLine("    return sortedTypes");
        _sb.AppendLine("    .Select(t => interceptors.First(i => i.GetType() == t))");
        _sb.AppendLine("    .ToList();");

        _sb.AppendLine("    }");
    }

    private static void GenerateSendAsyncMethod(List<(string CommandType, string ResultType)> allCommands)
    {
        _sb.AppendLine("    public async Task<Result<TResult>> SendAsync<TResult>(ICommand<TResult> command, CancellationToken cancellationToken = default)");
        _sb.AppendLine("    {");

        if (allCommands.Count > 0)
        {
            _sb.AppendLine("    // Type-safe dispatch with cached interceptor pipeline");
            _sb.AppendLine("    switch (command)");
            _sb.AppendLine("    {");
            for (int i = 0; i < allCommands.Count; i++)
            {
                var (commandType, resultType) = allCommands[i];
                var typeCommand = $"typedCommand{i}";

                var caseItem = $@"      case {commandType} {typeCommand}:
        {{
            // Create ambient transaction scope
            using var transactionScope = new TransactionScope(
            TransactionScopeOption.Required,
            TransactionScopeAsyncFlowOption.Enabled);

            var orderedInterceptors = GetOrderedCommandInterceptors<{commandType}, {resultType}>();
            var handler = _serviceProvider.GetRequiredService<ICommandHandler<{commandType}, {resultType}>>();

            // Tracks how many interceptors completed OnBefore — used for correct OnError unwinding
            var executedBeforeCount = 0;

            try
            {{
                // Execute OnBefore interceptors (ascending order)
                foreach (var interceptor in orderedInterceptors)
                {{
                    await interceptor.OnBeforeAsync({typeCommand}, cancellationToken).ConfigureAwait(false);
                    executedBeforeCount++;
                }}

                // Execute handler (can publish events, which will enlist in ambient transaction)
                var result = await handler.HandleAsync({typeCommand}, cancellationToken).ConfigureAwait(false);

                // Execute OnAfter interceptors (descending order - like a stack)
                for (int idx = orderedInterceptors.Count - 1; idx >= 0; idx--)
                    await orderedInterceptors[idx].OnAfterAsync({typeCommand}, result, cancellationToken).ConfigureAwait(false);

                // Complete transaction - triggers event commit
                transactionScope.Complete();

                return (Result<TResult>)(object)result;
            }}
            catch (Exception ex)
            {{
                // Don't call Complete() — automatic rollback
                // Only unwind interceptors that actually completed OnBefore (reverse order = stack unwinding)
                // e.g. if OnBefore[2] threw, only [1] and [0] get OnError — [2..n] were never entered
                for (int idx = executedBeforeCount - 1; idx >= 0; idx--)
                    await orderedInterceptors[idx].OnErrorAsync({typeCommand}, ex, cancellationToken).ConfigureAwait(false);
                throw;
            }}
            // TransactionScope.Dispose() is called here
            // - If Complete() was called: Commit (events persisted)
            // - If Complete() was NOT called: Rollback (events discarded)
        }}";
                _sb.AppendLine(caseItem);
            }

            _sb.AppendLine("        default:");
            _sb.AppendLine($"           throw new InvalidOperationException($\"No handler registered for command type {{command.GetType().Name}}\");");
        }
        else
        {
            _sb.AppendLine("        throw new InvalidOperationException(\"No command handlers registered\");");
        }

        _sb.AppendLine("    }");
        _sb.AppendLine("}");
    }

    private static void GenerateQueryAsyncMethod(List<(string QueryType, string ResultType)> allQueries)
    {
        _sb.AppendLine("    public async Task<Result<TResult>> QueryAsync<TResult>(IQuery<TResult> query, CancellationToken cancellationToken = default)");
        _sb.AppendLine("    {");

        if (allQueries.Count > 0)
        {
            _sb.AppendLine("    //Type-safe dispatch with cached interceptor pipeline");
            _sb.AppendLine("        switch (query)");
            _sb.AppendLine("        {");

            for (int i = 0; i < allQueries.Count; i++)
            {
                var (QueryType, ResultType) = allQueries[i];
                var typedQuery = $"typedQuery{i}";

                var caseItem = $@"      case {QueryType} {typedQuery}:
        {{
            var orderedInterceptors = GetOrderedQueryInterceptors<{QueryType}, {ResultType}>();
            var handler = _serviceProvider.GetRequiredService<IQueryHandler<{QueryType}, {ResultType}>>();

            // Tracks how many interceptors completed OnBefore — used for correct OnError unwinding
            var executedBeforeCount = 0;

            try
            {{
                // Execute OnBefore interceptors (ascending order)
                foreach (var interceptor in orderedInterceptors)
                {{
                    await interceptor.OnBeforeAsync({typedQuery}, cancellationToken).ConfigureAwait(false);
                    executedBeforeCount++;
                }}

                // Execute handler
                var result = await handler.HandleAsync({typedQuery}, cancellationToken).ConfigureAwait(false);

                // Execute OnAfter interceptors (descending order - like a stack)
                for (int idx = orderedInterceptors.Count - 1; idx >= 0; idx--)
                    await orderedInterceptors[idx].OnAfterAsync({typedQuery}, result, cancellationToken).ConfigureAwait(false);

                return (Result<TResult>)(object)result;
            }}
            catch (Exception ex)
            {{
                // Only unwind interceptors that actually completed OnBefore (reverse order = stack unwinding)
                // e.g. if OnBefore[2] threw, only [1] and [0] get OnError — [2..n] were never entered
                for (int idx = executedBeforeCount - 1; idx >= 0; idx--)
                    await orderedInterceptors[idx].OnErrorAsync({typedQuery}, ex, cancellationToken).ConfigureAwait(false);
                throw;
            }}
        }}";

                _sb.AppendLine(caseItem);
            }
            _sb.AppendLine("    default:");
            _sb.AppendLine("    throw new InvalidOperationException($\"No handler registered for query type {query.GetType().Name}\");");
        }
        else
        {
            _sb.AppendLine("        throw new InvalidOperationException(\"No query handlers registered\");");
        }

        _sb.AppendLine("    }");
        _sb.AppendLine("}");
    }

}