using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YAMCqrs.Core.SourceGeneration.Info;

internal static class SuppressionsHelper
{
    public static string GenerateCode(
        List<HandlerInfo> handlers,
        List<InterceptorInfo> interceptors)
    {
        var types = handlers
            .Select(h => h.FullTypeName)
            .Concat(interceptors.Select(i => i.FullTypeNameWithoutGenerics))
            .Where(t => !string.IsNullOrWhiteSpace(t))
            .Where(t => !t.Contains('<') && !t.Contains('>'))
            .Distinct()
            .ToList();

        if (types.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generation Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine();

        foreach (var type in types)
        {
            var target = GetTarget(type);
            sb.AppendLine("[assembly: SuppressMessage(");
            sb.AppendLine("    \"Microsoft.Usage\",");
            sb.AppendLine("    \"CA1812:Avoid uninstantiated internal classes\",");
            sb.AppendLine("    Justification = \"CQRS handlers and interceptors are instantiated by generated DI registration.\",");
            sb.AppendLine("    Scope = \"type\",");
            sb.AppendLine($"    Target = \"~T:{target}\")]\n");
        }

        return sb.ToString();
    }

    private static string GetTarget(string fullTypeName)
    {
        var index = fullTypeName.IndexOf('<');
        if (index < 0) return fullTypeName;
        var without = fullTypeName.Substring(0, index);
        var genericsPart = fullTypeName.Substring(index + 1, fullTypeName.LastIndexOf('>') - index - 1);
        var arity = genericsPart.Split(',').Length;
        return without + "`" + arity;
    }
}
